### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Kohleer** [Nivedha-Ramesh/Container-Loading-Problem#2]
Hi Nivedha,
I keep getting errors. It says "AttributeError: 'int' object has no attribute 'generate_pop'" in line 139. I wonder if you can help me fix these errors?

thanks

**Comment by Gangstart** [comment]
You must modify the main.py
"import population as gen"->
"from population import generate_pop"

**Comment by Gangstart** [comment]
您的邮件已收到 谢谢！
