### ISSUE TITLE
'int' object has no attribute 'generate_pop'

### ISSUE THREAD

**Issue by nimisha-tresa** [Nivedha-Ramesh/Container-Loading-Problem#3]
I am facing an issue in code of main.py line 139
  population = gen.generate_pop(box_params, NUM_OF_INDIVIDUALS, ROTATIONS)
AttributeError: 'int' object has no attribute 'generate_pop'

**Comment by Gangstart** [comment]
You must modify the main.py 
"import population as gen"->
"from population import generate_pop"
