### ISSUE TITLE
Interested in the container packing project

### ISSUE THREAD

**Issue by buztz** [Nivedha-Ramesh/Container-Loading-Problem#5]
Hi,

I'm interested in your 3d bin packing algorithm.
Want to know the efficiency of it , and maybe we can discuss adding some features to it.
Is there a way we can talk maybe via email?
betzalel.racovsky   at  gmail    
Thanks!

**Comment by Nivedha-Ramesh** [comment]
> Hi,
> 
> I'm interested in your 3d bin packing algorithm. Want to know the efficiency of it , and maybe we can discuss adding some features to it. Is there a way we can talk maybe via email? betzalel.racovsky at gmail Thanks!

Hello,
Sorry for the delayed response.
You can reach me at nivedharamesh9351@gmail.com, if you're still interested in this problem and want to work on extending it.

Cheers!
