### ISSUE TITLE
Curious on mutation

### ISSUE THREAD

**Issue by AkariMarisa** [Nivedha-Ramesh/Container-Loading-Problem#6]
Hi Mr. Ramesh! 

I've been reading your coding recently. When I read to the mutation part, it has something to do with the rotation. I wonder will this cause some unwanted result that user might don't want the rotation.

Here is the code
```
def mutate(offsprings, pm1, pm2,rotation=6):
    for child in offsprings.values():
        order = child['order']
        rotate = child['rotate']

        # ...

        # Second level of mutation
        for i in range(len(rotate)):
            if random.uniform(0, 1) <= pm2:
                rotate[i] = random.randint(0, rotation)   # This is what I wondered.

    return offsprings
```

If user only want the box rotate on z-index, or rather only can swap the length and width. Will this cause the box can rotate on length and height?

**Comment by Nivedha-Ramesh** [comment]
Hi

The rotation aspect is coded to either have 
1. No rotation (ROTATION = 0)
2. Rotations are allowed in the horizontal plane (ROTATION = 2)
3. Rotations are allowed in all three planes (ROTATION = 6)

So you can set the parameter accordingly.
The concept is explained in the attached report.

Cheers!
