### ISSUE TITLE
Can you explain the form of attributes of the dataset used in your project

### ISSUE THREAD

**Issue by wawanfirgiawan** [Nivedha-Ramesh/Container-Loading-Problem#7]
Please explain the attributes of the dataset used in this project.

![image](https://github.com/Nivedha-Ramesh/Container-Loading-Problem/assets/26499875/d3817384-7fbe-47e0-9395-21df58cb7e9f)

What parameters are used?

**Comment by Nivedha-Ramesh** [comment]
They are explained in the create dataset file. The dataset consists of the dimensions of the truck, the number of boxes it contains, the dimensions, volume and value associated with every box, and the total value associated with the truck for every datapoint.
